name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  NODE_VERSION: '22.18.0'
  PNPM_VERSION: '10'

jobs:
  prettier-lint-typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Prettier
        run: pnpm prettier --check .
      - name: Run lint
        run: pnpm lint
      - name: Run typecheck
        run: pnpm typecheck

  build:
    runs-on: ubuntu-22.04
    needs: [prettier-lint-typecheck]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Nuxt
        run: pnpm build
        env:
          NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.WALLETCONNECT_PROJECT_ID }}
          NEXT_PUBLIC_SEPOLIA_RPC_URL: ${{secrets.SEPOLIA_RPC_URL}}
